/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next')['BFormSelectOption']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    ColumnChart: typeof import('./src/components/dashboard/ColumnChart.vue')['default']
    EditableComment: typeof import('./src/components/general/EditableComment.vue')['default']
    InvoicesPerMonthList: typeof import('./src/components/editMonth/InvoicesPerMonthList.vue')['default']
    LocaleChanger: typeof import('./src/components/general/LocaleChanger.vue')['default']
    MonthlySum: typeof import('./src/components/general/MonthlySum.vue')['default']
    MonthOverview: typeof import('./src/components/general/MonthOverview.vue')['default']
    NavBar: typeof import('./src/components/general/NavBar.vue')['default']
    NumberInput: typeof import('./src/components/general/NumberInput.vue')['default']
    NumberOfInvoices: typeof import('./src/components/general/NumberOfInvoices.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleSelect: typeof import('./src/components/general/SingleSelect.vue')['default']
    SumPerContributionMember: typeof import('./src/components/general/SumPerContributionMember.vue')['default']
    ToggelSwitch: typeof import('./src/components/general/ToggelSwitch.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
